[package]
name = "mlar"
description = "A wrapper around the MLA library for common usecases"
version = "1.2.0"
authors = ["Camille Mougey <camille.mougey@ssi.gouv.fr>"]
edition = "2018"
license = "LGPL-3.0-only"
homepage = "https://github.com/ANSSI-FR/MLA"
repository = "https://github.com/ANSSI-FR/MLA"
readme = "../README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["wrap_help"] }
glob = "0.3"
mla = { path = "../mla", version = "1" }
curve25519-parser = { path = "../curve25519-parser", version = "0.3" }
rand = "0.8"
x25519-dalek = "1"
humansize = {version = "2", features = ["impl_style"]}
hex = "0.4"
# Could be made optional / feature to enable (for binary size)
tar = "0.4"
rand_chacha = "0.3"
lru = "0"

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
permutate = "0.3"
